### ISSUE TITLE
demo site

### ISSUE THREAD

**Issue by LennyLip** [zsiciarz/django-pgallery#1]
Did you have any demo site?

**Comment by faridgit** [comment]
![file](https://cloud.githubusercontent.com/assets/13736347/10282817/c8fe0206-6b8d-11e5-8889-bba78166fc3c.gif)

**Comment by faridgit** [comment]
ddddddd   ccccccc

**Comment by faridgit** [comment]
![03](https://cloud.githubusercontent.com/assets/13736347/10282852/04f98640-6b8e-11e5-9f7a-98764ad7dad2.gif)

**Comment by faridgit** [comment]
dfgg hgff

**Comment by zsiciarz** [comment]
Hi,
sorry, there's no real standalone demo at the moment. The only example I know is at my personal home site: https://siciarz.net/photos/.
