### ISSUE TITLE
index row requires 12400 bytes, maximum size is 8191

### ISSUE THREAD

**Issue by lynx-r** [zsiciarz/django-pgallery#2]
Hello,
I got error `index row requires 12400 bytes, maximum size is 8191` when saved image.

**Comment by zsiciarz** [comment]
Hi!
Try manually dropping the index on the `exif` field in the `pgallery_photo` table and see if it helps. (Note to self: I should probably experiment with JSONB instead of HStore for that field).

**Comment by skathakkal** [comment]
zsiciarz, I tried with JSONB and got similar error. Any suggestions?
