### ISSUE TITLE
Can't figure out how import pictures into example app

### ISSUE THREAD

**Issue by daavve** [zsiciarz/django-pgallery#3]
Hi,

I'm new to django, and I got the example app up and running with no pictures.  I was able to get into the admin interface.  But I a templatedoesnotexist message when I attempted to import some pics.

Please let me know what I am doing wrong.   Thanks,

-Dave

**Comment by zsiciarz** [comment]
Hi Dave,
Sorry for an oversight. Try installing django-pgallery from latest git commit and see if it helps.
https://github.com/zsiciarz/django-pgallery/commit/c64e0d4041339ebbd8b57c5938ec6b40f9354589 should fix your issue.

**Comment by daavve** [comment]
Thanks!  It works now.
