### ISSUE TITLE
problem basic

### ISSUE THREAD

**Issue by sagoyanfisic** [zsiciarz/django-pgallery#4]
Template error:
In template /home/lolkj/Djangoprojects/django-pgallery/example_project/pgallery/templates/pgallery/gallery_list.html, error at line 5
   no existe la relación «pgallery_gallery»
LINE 1: ..., "pgallery_gallery"."_description_rendered" FROM "pgallery_...

**Comment by zsiciarz** [comment]
Hi,
make sure `'pgallery'` is in your `INSTALLED_APPS` and don't forget to run `manage.py migrate`.

**Comment by sagoyanfisic** [comment]
hello, I did that steps start but even if I mounted this error to be

_Yancel Moises Salinas Gomez_
_Organizador GDG Open Lima__Linuxero_

2016-03-19 2:30 GMT-05:00 Zbigniew Siciarz notifications@github.com:
