### ISSUE TITLE
Default for ArrayField should be changed

### ISSUE THREAD

**Issue by itbabu** [zsiciarz/django-pgallery#5]
Hello Zbigniew,

https://github.com/zsiciarz/django-pgallery/blob/master/pgallery/models.py#L95-L96

The defaults should be changed:  from `[]` to `list`

https://docs.djangoproject.com/en/1.9/ref/contrib/postgres/fields/#django.contrib.postgres.fields.ArrayField

> If you give the field a default, ensure it’s a callable such as list (for an empty default) or a callable that returns a list (such as a function). Incorrectly using default=[] creates a mutable default that is shared between all instances of ArrayField.

I think the same should be applied to HStoreField

**Comment by zsiciarz** [comment]
Thanks!
